Remove build-depends cli-common-dev, mono-devel
* Were making mono5 fail to build on focal, with errors like
System.Security.Policy/Site.cs(81,36): error CS0246: The type or
namespace name 'SiteIdentityPermission' could not be found (are you
missing a using directive or an assembly reference?)
* Now monolite is used.
* At least cli-common-dev was a problem.
* This may not work with other releases than focal.

Change-Id: If1f8c9cead8daa57f101ee7defa3352ab97abef2