[mono] Use gcc 7, as using gcc 9 gives errors
* When building for Ubuntu 20.04, gcc 9 gives errors, like

/usr/lib/gcc/x86_64-linux-gnu/9/include-fixed/bits/statx.h:38:25:
error: missing binary operator before token "("
38 | #if __glibc_has_include ("__linux__/stat.h")

* This has not been a problem in Ubuntu 16.04 (gcc 5) or Ubuntu 18.04
(gcc 7).
* Specifying dependency as `g++-7 | g++ (<< 9)` so gcc-7 will be used
where available (Ubuntu 18.04 and 20.04), or otherwise a gcc with
version < 9 wil be used (gcc 5 on Ubuntu 16.04).
* Letting go of the >= 4.8 requirement probably doesn't matter much
since we aren't going to pull in such an old g++ or gcc version.
* `mono/debian/rules`: Setting CC and CXX to make sure gcc-7 is used
(and g++-7 in case CXX is used).
* This so far tested fine with focal amd64.

Change-Id: I60344d70055346979eb4cfdd9f6ed6a496f0c20f